### ISSUE TITLE
Missing user subscribed channels from allChannelsPlaylist.m3u

### ISSUE THREAD

**Issue by darshan0071990** [ForceGT/Tata-Sky-IPTV#11]
It seems that the option "Generate my Playlist" does not include all the channels that I have subscribed to. For example, I have subscribed to Sony SAB (non-HD), Star Movies HD, and a few more but there are not part of the generated Playlist m3u. 

I also ran "allChannels.py" still those channels are not included in the allChannels.json file.  It would be really great and helpful if someone looks into this.

**Comment by ForceGT** [comment]
Actually if `allChannels.py` cannot do it for you then, those channels are not available for live streaming. So no one other than Tata Sky themselves will be able to do something for it
