### ISSUE TITLE
Any Chances of adding other OTT

### ISSUE THREAD

**Issue by deepaksp** [ForceGT/Tata-Sky-IPTV#13]
any chances of you adding other ott live tv channel list ?
it will be great to generate voot, zee5, sony live tv from one app !

Thanks for the script and app, its really helpful !

**Comment by ForceGT** [comment]
I have thought about it, all you have to do is link me to all the resources and when I have enough time, then we actually could

**Comment by deepaksp** [comment]
https://github.com/botallen/repository.botallen
https://github.com/Vikassm73/AjaykRepo

i think these 2 project can help, i dont know much about python and kodi so cant understand much but it can help with api.

**Comment by Shra1V32** [comment]
Sure thing, But bash scripting only

**Comment by Shra1V32** [comment]
Not really comes under issues + It's not regarding Tsky IPTV
