### ISSUE TITLE
Categorization of the Channels into the Playlist

### ISSUE THREAD

**Issue by Nageshwar128** [ForceGT/Tata-Sky-IPTV#14]
Hey @ForceGT, That's really a great work by you, I'm hoping that we can expect all the channels being categorized in the playlist. It really makes hassle free.

**Comment by ForceGT** [comment]
Actually all the channels are already categorised as far as the latest code is concerned. The categorisation is based on what the Tata Sky portal gives as far as the category is concerned

**Comment by Nageshwar128** [comment]
Oh, Let me update my repo and check.
