### ISSUE TITLE
M3U is not generating

### ISSUE THREAD

**Issue by vgmuthu** [ForceGT/Tata-Sky-IPTV#17]
Hi,

Getting following error while trying to generate M3U file in both OTP as well as password method of login. Please advice. Thanks!

Could not generate JWT for channelId: 80
Didn't get license for channel: Id: 80 Name:SONY MAX HD
Continuing...Please get license manually for channel : SONY MAX HD
Response: {"code":"TKERR007","message":"Invalid epids"}
Could not generate JWT for channelId: 72
Didn't get license for channel: Id: 72 Name:REPUBLIC TV
Continuing...Please get license manually for channel : REPUBLIC TV
Response: {"code":"TKERR007","message":"Invalid epids"}Response: {"code":"TKERR007","message":"Invalid epids"}

**Comment by ForceGT** [comment]
Run `allChannels.py` once and try and then report back if it doesn't work

**Comment by vgmuthu** [comment]
This worked after running allChannels.py, thanks much :)
