### ISSUE TITLE
How to Generate m3u file with all the channels 

### ISSUE THREAD

**Issue by Pruthvi9277** [ForceGT/Tata-Sky-IPTV#19]
How to Generate m3u file with all the channels ,

Only getting User Subscribed channels even after updating the script by "niikhill"

**Comment by Pruthvi9277** [comment]
I'm sorry Gaurav  , I've already read the README, But the reason for asking this question is , As I came across a Telegram Group Where they are asking for the Tatasky Details and Providing all the channels in their play list, Due to which I thought to Comment here . I'm sorry .

Appreciate your Great work.

**Comment by niikhill** [comment]
> How to Generate m3u file with all the channels ,
> 
> Only getting User Subscribed channels even after updating the script by "niikhill"

I updated it for some other thing, script will still generate ur subscribed channels only.

**Comment by ProtonWolf** [comment]
can anyone tell me how to delete the channels that i dont want automatic daily

**Comment by ForceGT** [comment]
Very weird use case

**Comment by ProtonWolf** [comment]
its becz my family want them in there TV but i only want selected Channels, so plz is there any way to do this
