### ISSUE TITLE
Some channels not working

### ISSUE THREAD

**Issue by animeshrock** [ForceGT/Tata-Sky-IPTV#28]
Suddenly some channels stopped working Set Max (SD), Sony Wah, Disney as I got only this cannels not working, Tatasky source is okay as I found those are playing on Tatasky Watch and other unofficial playlists.

**Comment by niikhill** [comment]
Above listed channels working fine for me

Are you still facing the issue?

**Comment by animeshrock** [comment]
Tested multiple time but still the same. But all other channels working fine as usual.

**Comment by animeshrock** [comment]
Today found another channel Sony BBC Earth HD also not playing.

**Comment by ForceGT** [comment]
Check with the discussion group and reopen if required

**Comment by Shra1V32** [comment]
Try checking now
