### ISSUE TITLE
KODI Playback error

### ISSUE THREAD

**Issue by siddhusubbu** [ForceGT/Tata-Sky-IPTV#45]
Widevine Licence URL is very long, Is it possible to shorten it? KODI is not able to play with the long Licence URL.

**Comment by Shra1V32** [comment]
Mention about the Kodi Platform too.

**Comment by ForceGT** [comment]
Kodi is not officially supported

**Comment by siddhusubbu** [comment]
Kodi Windows 19.3 & 19.4 Matrix. The Android version works perfectly.
