### ISSUE TITLE
How can i register it please？

### ISSUE THREAD

**Issue by 239144498** [ForceGT/Tata-Sky-IPTV#47]
When I visit https://www.tataplay.com/, the following information appears:

403 ERROR
The request could not be satisfied.
The Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: bUdtB-D77qMavB8KkroxWL3eR7vrv631BHmXSXlTI1ECwl9gANp29w==

**Comment by Shra1V32** [comment]
Use Indian VPN
