### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by drtiwarir** [ForceGT/Tata-Sky-IPTV#49]
First of all - Amazing work
Congratulations and many thanks
The only problem is that while watching channels under "Knowledge" section, we can't change language, I was watching NatGeo Wild and I guess it was running Telugu.
Can we fix this ?

Regards

**Comment by Shra1V32** [comment]
Use other Video Players which support m3u files. Examples, TiviMate & OTT Navigator

**Comment by drtiwarir** [comment]
I tried both the players you mentioned (TiviMate & OTT Navigator) same issue

**Comment by drtiwarir** [comment]
Today it is running Telugu language on Sony BBC earth

**Comment by Shra1V32** [comment]
Nothing can be done on our side, This is purely the issue with TATAPLAY.
