### ISSUE TITLE
Error 400 when i try to generate playlist

### ISSUE THREAD

**Issue by K-VIJAYARAJAN** [ForceGT/Tata-Sky-IPTV#53]
Error while trying to generate play list on app. 
![Screenshot_20230428-192907](https://user-images.githubusercontent.com/92156623/235169048-fcef5deb-5826-4655-9b47-9002c8a791b7.png)

**Comment by Shra1V32** [comment]
Provide more information

**Comment by K-VIJAYARAJAN** [comment]
Error http 400 while trying to generate play list on app. Screenshot
attached

**Comment by Shra1V32** [comment]
App is deprecated, No longer supported.
