### ISSUE TITLE
One channel has wrong mpd link

### ISSUE THREAD

**Issue by rockydares** [ForceGT/Tata-Sky-IPTV#58]
A channel named 'Star Jalsha HD' mpd has wrong url, this starts with "https://delta.tatasky.net" which isn't valid. The right domain name for that channel is "https://bpprod6linear.akamaized.net"
Please make correction of that.

**Comment by ForceGT** [comment]
I think this should be updated with the daily generation!

**Comment by rockydares** [comment]
But unfortunately it's not getting updated. For about two or more weeks it shows same url. I am manually editing the url to make it work.

**Comment by Shra1V32** [comment]
Okay, we'll release a patcher. Any other channels having this issue?

**Comment by rockydares** [comment]
> Okay, we'll release a patcher. Any other channels having this issue?

I can see another channel named 'NKTV BANGLA' has wrong url. But I don't have it's correct mpd link.

**Comment by ForceGT** [comment]
But, how did you find that it is wrong?
What are you comparing it with?

**Comment by rockydares** [comment]
> But, how did you find that it is wrong? What are you comparing it with?

Here `https://raw.githubusercontent.com/ForceGT/Tata-Sky-IPTV/master/code_samples/allChannels.json` you can see the channel named 'Star Jalsha HD' has an mpd url `https://delta.tatasky.net/bpk-tv/irdeto_com_Channel_736/output/manifest.mpd` which will redirect to 'This site can’t be reached'. I am comparing with your previous 'allChannels.json' file which had correct link, but changed few weeks ago.

**Comment by gt-rapido** [comment]
All of these are server generated !

**Comment by Shra1V32** [comment]
> > Okay, we'll release a patcher. Any other channels having this issue?
> 
> I can see another channel named 'NKTV BANGLA' has wrong url. But I don't have it's correct mpd link.

These channels require manual patching work, As of now there's no motivation to continue the project, if you wish to reflect the changes soon then make donations to Shra1V32@apl to keep the project alive, else just keep waiting.

**Comment by rockydares** [comment]
lines = [line.replace('delta.tatasky.net', 'bpprod6linear.akamaized.net') for line in lines] # did the job for now I guess.
