### ISSUE TITLE
VLC showing blank screen (even though progress bar is moving)

### ISSUE THREAD

**Issue by theincognito-inc** [ForceGT/Tata-Sky-IPTV#6]
So, I cloned your repo, generated my userdetails, generated my channel playlist.
But VLC shows a blank screen (even though progress bar is moving)

![image](https://user-images.githubusercontent.com/16122455/125578279-ef44a1b3-6956-43da-84de-b5d4c2dd78f6.png)

Any ideas as to why?

**Comment by ForceGT** [comment]
DASH MPEG support in VLC is limited. It has a lot of issues with DRM protected DASH content as well as HLS if I am not wrong
So yeah, it won't work with VLC

You can try the chrome extension : Native MPEG-DASH + HLS(https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn?hl=en). It has no playlist support, you can watch the channels individually. It was supposed to be used on Android TV only, so Tivimate works fine for that and the above extension can help you on desktop

I've written how to do that in README
If you have any issues, I am already available in Telegram

**Comment by theincognito-inc** [comment]
Thanks a lot 👍🏼

**Comment by gadhiamitul41** [comment]
One can use Kodi + PVR IPTV CLIENT Addon + Widevine Plugin to play this playlist in Kodi.

**Comment by ForceGT** [comment]
Kodi acts weird with IPTV addon , I don't know why and that's why it has been mentioned in the README
